FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y \
  nmap \
  netcat \
  hydra \
  nikto \
  gobuster \
  metasploit-framework \
  curl \
  python3 \
  python3-pip \
  tcpdump \
  git \
  wget \
  vim

CMD ["/bin/bash"]
