version: "3.8"

services:
  dvwa:
    build: ./services/dvwa
    container_name: dvwa
    ports:
      - "${DVWA_PORT}:80"
    networks:
      - offensive_net
    restart: unless-stopped

  ftp:
    build: ./services/ftp
    container_name: ftp
    ports:
      - "${FTP_PORT}:21"
    networks:
      - offensive_net
    restart: unless-stopped

  ssh:
    build: ./services/ssh
    container_name: ssh
    ports:
      - "${SSH_PORT}:22"
    networks:
      - offensive_net
    restart: unless-stopped

  webdav:
    build: ./services/webdav
    container_name: webdav
    ports:
      - "${WEBDAV_PORT}:80"
    networks:
      - offensive_net
    restart: unless-stopped

  wordpress:
    build: ./services/wordpress
    container_name: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressdb
    depends_on:
      - db
    networks:
      - offensive_net
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - offensive_net
    restart: unless-stopped

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - offensive_net
    depends_on:
      - dvwa
      - ftp
      - ssh
      - webdav
      - wordpress
    restart: unless-stopped

  scoring:
    image: alpine
    container_name: scoring
    volumes:
      - ./flags:/flags:ro
    networks:
      - offensive_net
    restart: unless-stopped
networks:
  offensive_net:
    driver: bridge

volumes:
  db_data:
